### ISSUE TITLE
Tables instead of lists?

### ISSUE THREAD

**Issue by RobLoach** [Rabios/awesome-raylib#10]
I've found it difficult to quickly read through the lists. Might be handy to use tables instead???
https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

For example....

### Libraries and Frameworks

| Library | Description |
| --- | --- |
|  [raysan5/raylib](https://github.com/raysan5/raylib) | Simple and easy-to-use library to enjoy videogames programming. |
|  [SasLuca/rayfork](https://github.com/SasLuca/rayfork) | Single header and source, cross-platform, allocator-aware, C99 game libraries. |
|  [Rabios/rayport](https://github.com/Rabios/rayport) | Awesome C99, Header-Only, rayfork wrapper for raylib! |
|  [Rabios/rayutils](https://github.com/Rabios/rayutils) | Single-Header library that extends raylib with some awesome functionality! |
|  [raysan5/raygui](https://github.com/raysan5/raygui) | Simple and easy-to-use immediate-mode gui library. |
|  [victorfisac/Physac](https://github.com/victorfisac/Physac) | 2D physics header-only library for videogames developed in C using raylib library. |
|  [raysan5/rpng](https://github.com/raysan5/rpng) | Simple and easy-to-use library to manage png chunks. |
|  [raysan5/rres](https://github.com/raysan5/rres) | Simple and easy-to-use file-format to package resources. |
|  [raysan5/raudio](https://github.com/raysan5/raudio) | Simple and easy-to-use audio library based on miniaudio. |
|  [firststef/ECSlib](https://github.com/firststef/ECSlib)  | Library with ECS classes in C++ using raylib. |

**Comment by Rabios** [comment]
Thanks for your suggestion!
Will work on it and close this issue once i bring new stuff!

**Comment by Rabios** [comment]
Closing as i applied this to most sections!

**Comment by RobLoach** [comment]
This looks great!!! Thanks a lot.
